### ISSUE TITLE
`generate_csv` - generated CSV header is always alphabetically ordered  

### ISSUE THREAD

**Issue by jqnatividad** [dsietz/test-data-generation#90]
First off, thanks for this awesome library!

However, the generated csv's headers are alphabetically ordered.

The generated data itself is OK.

**Comment by dsietz** [comment]
@jqnatividad Thank you for submitting this bug. I'll take a look at it.

**Comment by dsietz** [comment]
Looks like the root cause is the the BTreeMap doesn't preserve the order of insertion.
https://github.com/dsietz/test-data-generation/blob/master/src/data_sample_parser.rs#L358

**Comment by jqnatividad** [comment]
As I understand it, BTreeMap sorts the keys.

Perhaps, use https://github.com/bluss/indexmap instead?

**Comment by dsietz** [comment]
It looks like that crate will work. Thanks for the suggestion. It will be a breaking change because any saved DataSampleParsers (DSP) from the prior version will not be able to be loaded from file into this new `DataSampleParser` struct.

**Comment by jqnatividad** [comment]
Time for test-data-generation 0.3 perhaps? 😉 

I'm keen to use it to power test data generation for [qsv](https://github.com/jqnatividad/qsv).

**Comment by dsietz** [comment]
Fix in development and passing. Will be included in release 0.3.0

**Comment by dsietz** [comment]
version 0.3.0 has been published to [crates.io](https://crates.io/crates/test-data-generation)

**Comment by dsietz** [comment]
This issue is resolved.

**Comment by jqnatividad** [comment]
Hi @dsietz , just wanted to let you know that I just published [qsv 0.22.0](https://crates.io/crates/qsv) with the generate command powered by test-data-generation.

Once again, thanks for this awesome library and I look forward to your feedback!

**Comment by dsietz** [comment]
@jqnatividad You're welcome. And much success with qsv.
