### ISSUE TITLE
Feature Request: Be able to specify CSV delimiter

### ISSUE THREAD

**Issue by jqnatividad** [dsietz/test-data-generation#91]
Right now, the delimiter is set to ",".

Would it be possible to have an additional parameter in `generate_csv` and `analyze_csv` to specify an alternate optional delimiter?

If the option argument is not set, then "," is used, otherwise, it uses the alternate delimiter for the csv::ReaderBuilder.

**Comment by dsietz** [comment]
I'll see what I can do.

**Comment by dsietz** [comment]
All tests passing in development. Will be added to version 0.3.0

**Comment by dsietz** [comment]
version 0.3.0 has been published to [crates.io](https://crates.io/crates/test-data-generation)
This enhancement is resolved.
